# Base configs
baseurl: "https://boqkiu.github.io/caodao/"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "G-1CWCVQ9895"

# UI configs
title: "caodao space"
subtitle: "building a space that holds meaning, breathes presence, and gives back through beauty and simplicity"
author: "boqkiu"
header:
 title: "caodao"
 subtitle: "living creative space"
footer:
 name: "Hey there, my name is Bohdan"
 bio: "I'm human after all from Ukraine. I'm not building a business. I'm building a space that holds meaning, breathes presence, and gives back through beauty and simplicity. Each contribution becomes: a plank, a brush, a cup of tea, a few hours of peace."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork this repo on github</a> ;)"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/boqkiu"

